# Generated by Django 3.1.7 on 2021-04-07 06:45

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


def initial_data(apps, schema_editor):
    admin = apps.get_model("restful_web_service", "employee")(id=1, full_name="admin", short_name="admin", login="admin", salt="21232f297a57a5a743894a0e4a801fc3", hash="dcc3458e93367f0da48d0d74f91883a0", isadmin=True, position_id=None)
    admin.save()
    rest_user = User.objects.create_user('rest_client', '', 'qwop')
    rest_user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StructureComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('structurecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.structurecomponent')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('restful_web_service.structurecomponent',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('structurecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.structurecomponent')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('salt', models.CharField(blank=True, max_length=32, null=True)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('isadmin', models.BooleanField(default=False)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restful_web_service.position')),
            ],
            bases=('restful_web_service.structurecomponent',),
        ),
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('systemcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.systemcomponent')),
            ],
            bases=('restful_web_service.systemcomponent',),
        ),
        migrations.CreateModel(
            name='SystemPart',
            fields=[
                ('systemcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.systemcomponent')),
            ],
            bases=('restful_web_service.systemcomponent',),
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('taskcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.taskcomponent')),
            ],
            bases=('restful_web_service.taskcomponent',),
        ),
        migrations.CreateModel(
            name='TaskLeaf',
            fields=[
                ('taskcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.taskcomponent')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PRO', 'In progress'), ('COM', 'Completed'), ('REJ', 'Rejected'), ('REV', 'Send to revision')], max_length=3)),
                ('duration', models.TimeField()),
                ('real_early_start', models.TimeField(blank=True, null=True)),
                ('real_late_start', models.TimeField(blank=True, null=True)),
                ('real_early_end', models.TimeField(blank=True, null=True)),
                ('real_late_end', models.TimeField(blank=True, null=True)),
                ('prop_early_start', models.TimeField(blank=True, null=True)),
                ('prop_late_start', models.TimeField(blank=True, null=True)),
                ('prop_early_end', models.TimeField(blank=True, null=True)),
                ('prop_late_end', models.TimeField(blank=True, null=True)),
                ('prev', models.ManyToManyField(blank=True, related_name='next', to='restful_web_service.TaskLeaf')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='restful_web_service.systemcomponent')),
            ],
            bases=('restful_web_service.taskcomponent',),
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation', to='restful_web_service.employee'),
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='restful_web_service.taskgroup'),
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonsibility', to='restful_web_service.employee'),
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='restful_web_service.systemgroup'),
        ),
        migrations.AddField(
            model_name='structurecomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='restful_web_service.division'),
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefact', to='restful_web_service.taskleaf')),
            ],
        ),
        migrations.RunPython(initial_data),
    ]
