# Generated by Django 3.1.2 on 2020-10-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_web_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
