# Generated by Django 3.1.2 on 2020-10-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful_web_service', '0002_auto_20201028_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomponent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restful_web_service.tasknode'),
        ),
    ]
