# Generated by Django 3.1.2 on 2020-10-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful_web_service', '0003_auto_20201028_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskleaf',
            name='previous',
            field=models.ManyToManyField(related_name='_taskleaf_previous_+', to='restful_web_service.TaskLeaf'),
        ),
        migrations.AlterField(
            model_name='taskcomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restful_web_service.tasknode'),
        ),
    ]
