# Generated by Django 3.1.2 on 2020-10-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_web_service', '0004_auto_20201028_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskleaf',
            name='next',
            field=models.ManyToManyField(related_name='_taskleaf_next_+', to='restful_web_service.TaskLeaf'),
        ),
    ]
