# Generated by Django 3.1.2 on 2020-10-28 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful_web_service', '0006_auto_20201028_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StructureComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='TaskNode',
            new_name='TaskGroup',
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('structurecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.structurecomponent')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('restful_web_service.structurecomponent',),
        ),
        migrations.AddField(
            model_name='structurecomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restful_web_service.division'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('structurecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.structurecomponent')),
                ('name', models.CharField(max_length=255)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restful_web_service.position')),
            ],
            bases=('restful_web_service.structurecomponent',),
        ),
    ]
