# Generated by Django 3.1.2 on 2020-10-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful_web_service', '0008_auto_20201028_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('structurecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.structurecomponent')),
            ],
            bases=('restful_web_service.structurecomponent',),
        ),
        migrations.CreateModel(
            name='SystemPart',
            fields=[
                ('structurecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restful_web_service.structurecomponent')),
            ],
            bases=('restful_web_service.structurecomponent',),
        ),
    ]
